name = "DocumenterQuarto"
uuid = "73f83fcb-c367-40db-89b6-8fd94701aaf2"
authors = ["Joey Carpinelli <joey@loopy.codes>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Quarto = "d7167be5-f61b-4dc9-b75c-ab62374668c5"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1"
Dates = "1"
DocStringExtensions = "0.9"
Documenter = "1.8"
Git = "1.3"
IOCapture = "0.2"
InteractiveUtils = "1"
Markdown = "1"
Quarto = "1"
TOML = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
